name: classic-template-action
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 */24 * * *"
jobs:
  build:
    permissions:
      issues: read
      pull-requests: read
      repository-projects: read
      statuses: read
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: classic-template
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, repositories
          plugin_lines: yes
